
export const FETCH_INGREDIENTS_REQUEST = 'FETCH_INGREDIENTS_REQUEST'
export const FETCH_INGREDIENTS_SUCCESS = 'FETCH_INGREDIENTS_SUCCESS'
export const FETCH_INGREDIENTS_ERROR = 'FETCH_INGREDIENTS_ERROR'

export const POST_ORDER_REQUEST = 'POST_ORDER_REQUEST'
export const POST_ORDER_SUCCESS = 'POST_ORDER_SUCCESS'
export const POST_ORDER_ERROR = 'POST_ORDER_ERROR'

export const SELECT_INGREDIENT = "SELECT_INGREDIENT";

export const GET_CONSTRUCTOR_INGREDIENTS = "GET_CONSTRUCTOR_INGREDIENTS";
export const PUSH_CONSTRUCTOR_INGREDIENT = "PUSH_CONSTRUCTOR_INGREDIENT";
export const DELETE_CONSTRUCTOR_INGREDIENT = "DELETE_CONSTRUCTOR_INGREDIENT";
export const REFRESH_CONSTRUCTOR = "REFRESH_CONSTRUCTOR";
export const SET_DEFAULT_CONSTRUCTOR = 'SET_DEFAULT_CONSTRUCTOR'

export const COUNT_ORDER_SUM = 'COUNT_ORDER_SUM'

export const OPEN_INGRD_MODAL = 'OPEN_INGRD_MODAL'
export const OPEN_CONSTRUCT_MODAL = 'OPEN_CONSTRUCT_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'

export const LOGIN = 'LOGIN'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const LOGOUT = 'LOGOUT';

export const REFRESH_TOKEN_REQUEST = 'REFRESH_TOKEN_REQUEST';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAILED  = 'REFRESH_TOKEN_FAILED';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILED = 'GET_USER_FAILED';