export const INGREDIENTS_DATA = 'INGREDIENTS_DATA'

export const ORDER_DATA = 'ORDER_DATA'
export const RESET_CONSTRUCTOR = 'RESET_CONSTRUCTOR'

export const PLUS_COUNTER = 'PLUS_COUNTER'
export const MINUS_COUNTER = 'MINUS_COUNTER'
export const SHUFFLE_INGREDIENT = 'SHUFFLE_ITEM'